import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <form action="/api/auth/sign-in" method="POST">
            <button>Sign In</button>
          </form>
        </header>
        {children}
      </body>
    </html>
  );
}
